# Generated by Django 4.1.2 on 2024-03-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0003_staffnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffnotification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
