# Generated by Django 4.1.2 on 2024-04-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0008_studentfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeedback',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
