# Generated by Django 4.1.2 on 2024-04-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0009_studentfeedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafffeedback',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
